# Site settings
title: U.S. Web Design Standards Jekyll Template
description: U.S. Web Design Standards Jekyll Template
baseurl: "/us-web-design-standards-jekyll-template"
url: ""
uswds: "/assets/uswds"

# Build settings
kramdown:
  hard_wrap: true

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: main
